### ISSUE TITLE
Booting Minix 2.0.2 on PC XT fails silently

### ISSUE THREAD

**Issue by rationalism** [dbalsom/martypc#73] opened 2023-12-08 23:40 UTC
Hi! I'm trying to install Minix 2.0.2 using the emulator. (Note that this is a different version, and a different error, than the issue in #61 ). Disk images are available here:

https://www.minix-vmd.org/pub/minix/2.0.2/

I tried loading the `TINYROOT.MNX` (renamed to `TINYROOT.IMG`) image to floppy drive A: and booting. However, the boot silently failed for unclear reasons; the disk was ignored, and the boot processed finished at the IBM BASIC terminal as if there was no disk. There was no error message displayed; I tried to run with `RUST_LOG=trace` per the instructions, but there were so many messages that any error would have immediately scrolled off the screen. 

I am using Ubuntu 22.04 on a laptop, and am on the branch `main`, commit ID `23617a7500192f35a13ffd65539ef1171581a691`.

**Comment by rationalism** [comment] 2023-12-08 23:51
@dbalsom Hey, I found the answer to this - the disk image wasn't a full 360 KB. I appended zeroes with `dd` until it was 360 KB, and now it boots.

Before I expanded the floppy disk image, I also tried booting the image `XTBOOT.IMG`/`XTBOOT.MNX`, which was suggested in case of an error. This floppy booted successfully, and displayed the Minix prompt, which asked the user to insert the root floppy, then hit a key. However, when I ejected the old floppy and inserted the root floppy (`TINYBOOT.IMG`/`TINYBOOT.MNX`), the emulator read for a few seconds, then crashed with "Read error A0".

**Comment by dbalsom** [comment] 2023-12-08 23:59
Other than adding a yaml file to play around with Github CI, the main branch is positively ancient, and has none of the other minix fixes.

**Comment by dbalsom** [comment] 2023-12-09 00:02
I don't really have a usable development branch for you to try at the moment. multi_monitor is the newest branch, but it also requires you to have a completely new configuration file.

**Comment by dbalsom** [comment] 2023-12-09 00:14
I do need to show some sort of error message in the GUI when a disk image fails to load.

**Comment by rationalism** [comment] 2023-12-09 00:28
@dbalsom Thank you! I tried cherry-picking this commit:

https://github.com/dbalsom/martypc/commit/392d73c0fbb53b2b5266f6803ff3d338382951fe

and unfortunately it still hung after hitting the `=` key. I tried checking out that commit and running, and it failed with this error message:

```
warning: `martypc_pixels_desktop` (lib) generated 55 warnings (run `cargo fix --lib -p martypc_pixels_desktop` to apply 30 suggestions)
    Finished release [optimized] target(s) in 1m 06s
     Running `target/release/martypc`
Failed to parse configuration file. There may be a typo or otherwise invalid toml:
missing field `keyboard_type` for key `machine` at line 188 column 1
```

Happy to keep trying if there's a valid config file available for a later commit

**Comment by lautis0503** [comment] 2023-12-09 07:48
> Other than adding a yaml file to play around with Github CI, the main branch is positively ancient, and has none of the other minix fixes.

That is.

I've tried MINIX 2.0 before, but won't report the issue until MINIX 1.1 and 1.5 are confirmed to run correctly. So let's forget MINIX 2.0 now.

As for configuration file, it will not be updated in the development branch. Read the code and modify it yourself like I did before.

**Comment by dbalsom** [comment] 2023-12-09 14:32
> As for configuration file, it will not be updated in the development branch. Read the code and modify it yourself like I did before.

Well, it could be. The original idea of the /install folder is that I'd have the assets/files that MartyPC needed to run in there, so you could use it as a base for your MartyPC installation. So I just need to check in an updated toml there. 

At this point it would be a lot to ask someone to try to derive the new config format from the code. I've moved the definition of the toml-mapped data structures from the config module to the modules that own them, so you'd be looking all over them.  And there's now window definitions, and shader presets, and video card declarations, and all sorts of new stuff, and well... it's not just a matter of setting a few missing flags anymore.

I've been trying to make most of the config fields optional so that if I add something it doesn't immediately break with older configs - it will just use some sensible default instead - but that's not always possible.

The new display manager system is mostly stable with just a few UI settings needing to be wired up. The new scaler/shader system is stable. EGA is still a work in progress but the fundamental changes needed for it are done and so most of what's remaining there wont' affect the rest of the core.  So this weekend I hope to get everything merged back down to the 0.2.0 branch.  

I will try to remember to check in the config and tag 'stable' commits going forward so more people can effectively test the development branches.

**Comment by dbalsom** [comment] 2023-12-09 18:30
@lautis0503 @rationalism  

I've merged things down and set the default branch to 0.2.0.  

If you want to check it out and test any Minix stuff, I have confirmed that you can clone the repo, 'cd martypc\install', and 'cargo run', and the emulator will start with the included martypc.toml. It's very different than the existing toml, but there are enough comments in there it should be self-explanatory.

I checked in GlaBIOS (with permission) so the emulator can run straight from the repo.  
An external icon file is no longer required.

**Comment by rationalism** [comment] 2023-12-09 20:14
@dbalsom Thanks a lot! Tried this, it compiled and ran successfully

- Initially, a bunch of debug windows appeared in the emulator and could not be closed, but I fixed this by disabling debug mode in the .toml config file
 - The error message "epaint: WARNING: pixels_per_point (dpi scale) have changed between text layout and tessellation. You must recreate your text shapes if pixels_per_point changes." was printed over and over on the command line extremely rapidly (tens of thousands of times per second).
 - The mouse cursor appears to be slightly misplaced (ie., the menu option that gets highlighted is something like ~40 pixels to the lower right of where the tip of the mouse cursor arrow icon is displayed on the screen)
 - Minix 2.0.2 disk image hangs after booting as before (boot, hit "=", a loading screen is displayed with a table of available memory, then hangs)
 - CPU usage appears to be very high with the new version (my fan quickly spins up), even when nothing is happening on the emulator

**Comment by dbalsom** [comment] 2023-12-09 20:54
> @dbalsom Thanks a lot! Tried this, it compiled and ran successfully


I think all these things (except the Minix issue) are basically related.

I think you have DPI scaling enabled (not really sure how this works in linux)
- something is going wrong with dpi scaling and making egui unhappy
- the mouse cursor is off because the dpi scaling isn't working
- the mouse cursor being off meant you couldn't close the debug windows
- your cpu usage is extremely high because printing a log entry to the console is relatively expensive to do, and it's being spammed

can you give me more info about your graphics card / window manager etc ? if you can find your DPI settings somewhere that would be useful.

**Comment by rationalism** [comment] 2023-12-09 21:05
@dbalsom I'm running an RTX 3060 on Ubuntu 22.04, happy to run other diagnostics if that would help

**Comment by dbalsom** [comment] 2023-12-09 21:19
> @dbalsom I'm running an RTX 3060 on Ubuntu 22.04, happy to run other diagnostics if that would help

Well, the good news is turning on DPI scaling in Windows produces the same error, so it's just something buggy with my DPI handling in the new display manager. I'll update here when I have a fix to try.

**Comment by lautis0503** [comment] 2023-12-10 06:25
Got three compiling errors.

```
Compiling martypc_pixels_desktop v0.2.0 (...\martypc\frontends\martypc_pixels_desktop)
error[E0446]: private type `MouseData` in public interface
   --> frontends\martypc_pixels_desktop\src\emulator\mod.rs:65:5
    |
65  |     pub mouse_data: MouseData,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
    |
   ::: frontends\martypc_pixels_desktop\src/lib.rs:182:1
    |
182 | struct MouseData {
    | ---------------- `MouseData` declared as private

error[E0446]: private type `KeyboardData` in public interface
   --> frontends\martypc_pixels_desktop\src\emulator\mod.rs:66:5
    |
66  |     pub kb_data: KeyboardData,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
    |
   ::: frontends\martypc_pixels_desktop\src/lib.rs:232:1
    |
232 | struct KeyboardData {
    | ------------------- `KeyboardData` declared as private

error[E0446]: private type `Counter` in public interface
   --> frontends\martypc_pixels_desktop\src\emulator\mod.rs:67:5
    |
67  |     pub stat_counter: Counter,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
    |
   ::: frontends\martypc_pixels_desktop\src/lib.rs:111:1
    |
111 | struct Counter {
    | -------------- `Counter` declared as private
```

rustc/cargo 1.72.0 in Windows.

**Comment by lautis0503** [comment] 2023-12-10 06:47
MINIX 1.1 boots now, but not MINIX 1.5

**Comment by lautis0503** [comment] 2023-12-11 16:37
This is floppy images of [MINIX 1.5](https://mirror.math.princeton.edu/pub/oldlinux/Linux.old/Minix/old/1.5/ps/).
Attention, some files are in wrong size ('cause they are expected to be written to real floppies), so you need to expand them to 720K.
I got a file from somewhere on the Internet explaining the floppy images.

>Minix 1.5 3"1/2 for the IBM PC,
XT, AT, 386 and PS/2

>Disk numbering:
01: PC Boot Disk
02: AT Boot Disk
03: Universal Boot Disk
04: Root File System
05: System Binaries #1 (/usr)
06: System Binaries #2
07: System Binaries #3
08: Operating System Sources
09: Command Sources #1
10: Command Sources #2
11: Networking Sources
12: Boot Disk with ST 506 Hard Disk

>3.5" 720K disks (no double step on imagedisk),
Universal Boot Disk uses BIOS calls for disk
access, so should work often if not always,
but should be slower too.
Disk 3 boots succesfully in VMWare, still
has problems in VPC.

>standard user= ast
password = Wachtwoord
root password = Geheim

**Comment by lautis0503** [comment] 2023-12-11 16:42
[MINIX 1.5 REFERENCE MANUAL](https://github.com/olegslavkin/linux-0.01/blob/master/manual/minix-15-reference-manual-1991.pdf)

**Comment by rationalism** [comment] 2023-12-16 01:45
@dbalsom Tried pulling the branch and running again, got this error during compilation:

```
error[E0599]: no method named `set_debug_on_hover` found for struct `egui::Context` in the current scope
   --> lib/frontend/marty_egui/src/lib.rs:415:22
    |
415 |             egui_ctx.set_debug_on_hover(true);
    |                      ^^^^^^^^^^^^^^^^^^ method not found in `Context`

For more information about this error, try `rustc --explain E0599`.
warning: `marty_egui` (lib) generated 6 warnings
error: could not compile `marty_egui` (lib) due to previous error; 6 warnings emitted
```

**Comment by rationalism** [comment] 2023-12-16 01:47
@dbalsom Update: `cargo run` worked but `cargo run -r` had the compilation error above

**Comment by dbalsom** [comment] 2023-12-16 02:10
> @dbalsom Update: `cargo run` worked but `cargo run -r` had the compilation error above

already fixed. this function only exists in egui in debug mode, which is odd... why not just stub it out in release?

**Comment by rationalism** [comment] 2023-12-16 03:10
@dbalsom Here is the result of running this command in the most recent version of `version_0_2_0`, then trying to boot the Minix 2.0.2 floppy:

`RUST_LOG=debug,naga=error,wgpu_core=error,marty_core::devices::hdc=trace cargo run -r &> log.txt`

[log.txt](https://github.com/dbalsom/martypc/files/13691195/log.txt)

**Comment by dbalsom** [comment] 2023-12-16 03:30
well, no unimplemented command warnings.. the xebec controller protocol is rather similar to the floppy disk controller, in that is is annoying and filled with lots of random little status bits.  I imagine minix is unhappy about the way i set or don't set one particular bit.

**Comment by krangerich** [comment] 2024-01-23 15:48
> It loads the RAM disk extremely slowly. I am not sure if that's normal or not.

How is it compared to Minix 1.2? I'm currently studying 1.2 in depth (your debugger saved my sanity multiple times). 
With 4.77 Mhz and normal floppy timings, it takes ~60 seconds to load a 240kb ram disk on 86box (using 360kb images) - that's why I'm usually running it with 16 Mhz and turbo timings.

**Comment by dbalsom** [comment] 2024-01-26 03:56
> > It loads the RAM disk extremely slowly. I am not sure if that's normal or not.
> 
> How is it compared to Minix 1.2? I'm currently studying 1.2 in depth (your debugger saved my sanity multiple times). With 4.77 Mhz and normal floppy timings, it takes ~60 seconds to load a 240kb ram disk on 86box (using 360kb images) - that's why I'm usually running it with 16 Mhz and turbo timings.

I haven't tried 1.2.  1.5 loads very quickly now, just a few seconds. But I don't have proper floppy drive timings either, so it's probably much faster than hardware.

**Comment by dbalsom** [comment] 2024-01-26 04:00
Minix 2.0 is loading much faster now after I implemented the Read Sector ID command for Minix 1.5 
Minix 1.5 issues the command and waits for an interrupt, forever, which causes a hang if the drive does not respond.
Minix 2.0 times out instead, which just resulted in very slow drive operation.

![image](https://github.com/dbalsom/martypc/assets/7229541/3df1dc43-2687-4e0d-a824-8b57c4b07b32)

I think that's all the Mixixes working, now.  I just need to figure out how to install to the hard drive...

**Comment by lautis0503** [comment] 2024-01-26 11:27
> I think that's all the Minixes working, now. I just need to figure out how to install to the hard drive...

There's guides in _MINIX 1.5 Reference Manual_. But that's not quite easy as MS-DOS or contemporary OSes.

**Comment by lautis0503** [comment] 2024-01-29 16:20
![screenshot004](https://github.com/dbalsom/martypc/assets/16025671/88464f92-fa7f-4809-a36e-e90e9521ec02)

MINIX 2.0.2. TINYBOOT and then TINYUSR1. Two **_Unrecoverable write error_**.
Machine config is 5160, CGA, two 360K floppies, no hard drive.

**Closed** 2024-04-02 02:26 UTC
Labels: bug
